In [2]:
import numpy as np

In [ ]:
#aggregate functions
ar=np.array(([11,22,33],[100,100,100],[7,8,9]))
print(ar)
ar=np.arange(1,10).reshape(3,3)
print(ar)

[[ 11  22  33]
 [100 100 100]
 [  7   8   9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#broadcasting
a1=np.arange(1,9)
print(a1)
a2=np.arange(11,99,11)
print(a2)
print(a1+a2)
print(a1*a2)
print(a1.min())
print(a1.max())
print(a1.mean())
print(len(a1))
print(np.quantile(a2,0.5))

La1=[1,2,3,4,5,6,7,8]
la2=[11,22,33,44,55,66,77,88]
print(La1+la2) #it concatenates


[1 2 3 4 5 6 7 8]
[11 22 33 44 55 66 77 88]
[12 24 36 48 60 72 84 96]
[ 11  44  99 176 275 396 539 704]
1
8
4.5
8
49.5
[1, 2, 3, 4, 5, 6, 7, 8, 11, 22, 33, 44, 55, 66, 77, 88]


In [ ]:
print(ar)
print(ar<5)
print(ar[ar<5])
ar=np.random.randint(1,100,50)
print(ar)
print(ar[(ar<50)&(ar<80)])
a1=np.random.randint(1,100,9).reshape(3,3)
a2=np.random.randint(1,100,9).reshape(3,3)
print(a1)
print(a2)
print(np.concatenate([a1,a2],axis=0)) #row concatenate
print(np.concatenate([a1,a2],axis=1))  #col concatenate
print(np.vdot(a1,a2)) #mult ka sum
print((a1*a2).sum())  #same as above



[59 83 97 61 66 46 34 80 85 47 62 33  7 83 38 77 91 16 84 53  2 66 36 88
 65 19 42 65 50 22 94 47 18 54 21 92 30 52 41 74 36  6 78 63 84 92 21 48
 52 27]
[False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
[2]
[88 45 27 59 46 38  7  4 15 55 80 80 12 33 22  1 11 67 69 28  1 35  4 43
 78  2 58 82 56 22 16 13 49 74 77 84 25 30 97 23 78 76 10  8 39 14 63 57
 66  4]
[45 27 46 38  7  4 15 12 33 22  1 11 28  1 35  4 43  2 22 16 13 49 25 30
 23 10  8 39 14  4]
[[12 15  2]
 [48 66 63]
 [27 29  2]]
[[37 83  1]
 [54 22 55]
 [61 48 43]]
[[12 15  2]
 [48 66 63]
 [27 29  2]
 [37 83  1]
 [54 22 55]
 [61 48 43]]
[[12 15  2 37 83  1]
 [48 66 63 54 22 55]
 [27 29  2 61 48 43]]
12325
12325


In [ ]:
#ravel and flatten
print(a1)
fa=a1.flatten()  #generates duplicate copies also
print(fa)
fa[0]=100
print(fa)
print("\n")

print(a2)
ra=a2.ravel() #generates REFERENCE COPY IN 1S ARRAy
ra[0]=100
print(ra)

print("\n")

print(np.split(ra,3))  #splits the array
rav=np.vstack(ra)   #vertically stacks the array
print(np.hstack(rav))  #horizonatally
print(np.histogram(ra,bins=3))
print("\n")

print(ra.sort())
A=np.random.randint(1,100,50)
print(np.argsort(A))  #index deta 
print(A[np.argsort(A)])  #ascending

[[12 15  2]
 [48 66 63]
 [27 29  2]]
[12 15  2 48 66 63 27 29  2]
[100  15   2  48  66  63  27  29   2]


[[ 48  54  55]
 [ 61  83 100]
 [100 100 100]]
[100  54  55  61  83 100 100 100 100]


[array([100,  54,  55], dtype=int32), array([ 61,  83, 100], dtype=int32), array([100, 100, 100], dtype=int32)]
[100  54  55  61  83 100 100 100 100]
(array([3, 1, 5]), array([ 54.        ,  69.33333333,  84.66666667, 100.        ]))


None
[ 4  9 21 42 35  0 18 19 34 28  1 32  6 39 22 13 10 16 23 30 26 15 41 11
 44 36 38  2 37 17 31 40 46  8 24 29 20 47  5 27 49 12 45 14 25  7 48 33
 43  3]
[ 3  7  8 14 15 15 16 18 21 23 23 28 31 35 41 41 44 44 45 45 47 47 49 52
 53 53 54 55 55 56 56 57 58 59 66 69 74 75 76 79 82 83 84 84 88 91 91 91
 95 99]
