1. Create a NumPy array of numbers from 1 to 20 and reshape it into a 4x5 matrix.

In [1]:
import numpy as np

In [5]:
print(np.arange(1,21).reshape(4,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


2. Generate an array of 10 random integers between 1 and 100 and find their mean, median, and standard deviation.

In [ ]:
a=np.random.randint(1,100,10)
print(a)
print(a.mean())  #mean
print(np.quantile(a,0.5))  #median
print(np.median(a))    #median  
print(np.std(a))   #standard dev

[20 49 14 73 35 30 32 25 10 16]
30.4
27.5
27.5
17.928747864811978


3. Create two arrays [1,2,3] and [4,5,6] and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
ar1=np.array([1,2,3])
print(ar1)
print("\n")

ar2=np.array([4,5,6])
print(ar2)
print("\n")

print(ar1+ar2) #add
print(ar1-ar2)  #subtract
print(ar1*ar2)   #multiply
print(ar1/ar2)  #divide

[1 2 3]


[4 5 6]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


4. Given an array [10, 20, 30, 40, 50], use np.where to label values greater than 25 as 'High' and others as 'Low'.

In [37]:
ar=np.array([10,20,30,40,50])
print(ar)
a=ar[ar>25]
print(a)
b=ar[ar<25]
print(b)
print(np.where(ar>25,"high","low"))


[10 20 30 40 50]
[30 40 50]
[10 20]
['low' 'low' 'high' 'high' 'high']


5. Generate a 3x3 identity matrix using NumPy.

In [38]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


6. Create an array of 15 random numbers and find the maximum and minimum values with their indices.

In [53]:
arr=np.random.randint(1,100,15)
print(arr)

print("indices",arr.argsort())
print("sorted array" ,arr[np.argsort(arr)])
print("max value", max(arr))
print("min value",min(arr))

[68  8 12 18 84 71 58 97 67 50 62 63 74  9 69]
indices [ 1 13  2  3  9  6 10 11  8  0 14  5 12  4  7]
sorted array [ 8  9 12 18 50 58 62 63 67 68 69 71 74 84 97]
max value 97
min value 8


7. Create a 1D array of 12 elements and reshape it into a 3D array of shape (2,2,3).

In [56]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("array = " , arr)

print("\n")

print(arr.reshape(2,2,3))



array =  [ 1  2  3  4  5  6  7  8  9 10 11 12]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


8. Create an array of 100 random numbers and find the top 5 maximum values using np.argsort.

In [67]:
arr=np.random.randint(1,200,100)
print("array = " , arr)
print("\n")

a=arr[np.argsort(arr)]
print("sorted = ",a)
print("\n")

print("top 5 max" , a[100:94:-1])

array =  [174  75 162 101 190 186  84 101 122 157  64   9  64 112  50 145 124 113
 187 105 152  30 184  98  65  70 184 129  27 153  18  49  37  30 149   5
 197 144 170  79  28  57  14 106  69  72  99  69  79   7 115  95  10  47
 148  32  67 173  42 129 128  41  34 137 194 180  30 153 171 186  52  48
 170  11  44  76 151 138  24 194   1 110  76   2 182  49  55 151 123 143
 128  27  84  58 178  77 140 182 179 198]


sorted =  [  1   2   5   7   9  10  11  14  18  24  27  27  28  30  30  30  32  34
  37  41  42  44  47  48  49  49  50  52  55  57  58  64  64  65  67  69
  69  70  72  75  76  76  77  79  79  84  84  95  98  99 101 101 105 106
 110 112 113 115 122 123 124 128 128 129 129 137 138 140 143 144 145 148
 149 151 151 152 153 153 157 162 170 170 171 173 174 178 179 180 182 182
 184 184 186 186 187 190 194 194 197 198]


top 5 max [198 197 194 194 190]


9. Write a NumPy program to generate an array of 10 values evenly spaced between 0 and 1.

In [75]:

print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


10. Create a 4x4 matrix of random integers and extract the diagonal elements using np.diag.

In [ ]:
arr=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print(arr)

print(np.diag(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  6 11]


11. Generate a 1D array of size 20 with random integers and find all even numbers using boolean indexing.

In [91]:
arr=np.random.randint(1,100,20)
print(arr)

print(np.where(arr%2==0,True,False))

[83 24 96 69 48 89 66 80 56 97 28  9 47 72  8 61 38 10 69 39]
[False  True  True False  True False  True  True  True False  True False
 False  True  True False  True  True False False]


12. Create a NumPy array with repeated elements [1,2,3,4] repeated 3 times.

In [95]:
print(np.repeat((1,2,3,4),3))


[1 1 1 2 2 2 3 3 3 4 4 4]


13. Generate a 2D 5x5 matrix of random integers and replace all values greater than 50 with 0.

In [100]:
arr=np.random.randint(1,100,25)
print(arr.reshape(5,5))
print("\n")

print(np.where(arr>50,0,arr))


[[47 45 98 20 83]
 [ 4 98 38 81 54]
 [10 56 47 95 32]
 [ 7 55 36 87 46]
 [ 4 54 28 59  5]]


[47 45  0 20  0  4  0 38  0  0 10  0 47  0 32  7  0 36  0 46  4  0 28  0
  5]


14. Create an array [5,10,15,20,25,30] and compute the cumulative sum using np.cumsum.

In [101]:
arr=np.array([5,10,15,20,25,30])
print(np.cumsum(arr))

[  5  15  30  50  75 105]


15. Create two 3x3 matrices and perform matrix multiplication using np.dot.

In [103]:
arr1=np.random.randint(1,10,9)
arr2=np.random.randint(1,10,9)
print("arr1 = ",arr1)
print("arr2=", arr2)
print(np.dot(arr1,arr2))

arr1 =  [8 3 1 5 3 9 8 5 8]
arr2= [4 2 8 7 7 1 6 6 9]
261


16. Generate a random 6x6 matrix and compute row-wise and column-wise sums.

In [119]:
arr=np.random.randint(1,30,36)
arr=arr.reshape(6,6)


In [121]:
arr.sum(axis=0)

array([ 94,  94,  76,  69,  78, 111])

17. Create a 1D NumPy array of 10 integers and compute their squares using vectorized operations.

In [109]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr*arr)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]


18. Write a NumPy program to check for missing values (NaN) in an array.

In [128]:
arr=np.array([1,np.nan,3,np.nan])
np.isnan(arr).sum()

np.int64(2)

19. Generate a 3x3 matrix with random integers and sort it along rows and columns.

In [ ]:
arr=np.random.randint(1,10,9)
print(arr.reshape(3,3))
print(arr[np.argsort(arr)])

[[8 8 1]
 [2 7 5]
 [8 8 1]]
[1 1 2 5 7 8 8 8 8]


20. Create a NumPy array of shape (4,4) with random integers and flatten it into a 1D array.

In [117]:
arr=np.random.randint(1,20,16)
print(arr.reshape(4,4))
print("\n")

print(arr.flatten())

[[ 7 14 11  9]
 [12  3  3 12]
 [16 15  4 10]
 [ 7 16 14 15]]


[ 7 14 11  9 12  3  3 12 16 15  4 10  7 16 14 15]
