numbers in python 
data:array
homogenius single data type exists
1d=[rows]
2d=[rowsXcolumns]
3d=[tablesXrowsXcolumns]


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np    #we gave name to it

In [4]:
print(np.array([1,2,3,4]))

print("\n")

print(np.array([1,2,3.5,4])) #gives all float

print("\n")

print(np.array([1,2,'3',4])) #gives all string

print("\n")

print(np.array([1,2,4,-128],dtype='int8'))    #-128 to 127 can exist(int8,16,32,64 extsts)

print("\n")

print(np.array(['ram','shyam','hari','murli'],dtype='<U4'))  #gives len<4

print("\n")

print(np.array(['',2,1,0,True,False],dtype=bool))  #gives in bool

print("\n")

print(np.array([None,1,2])) #we do not put none as a missing value

print("\n")

print(np.isnan(np.array([np.nan,1,2])))  #we write np.nan for missing value

print("\n")


[1 2 3 4]


[1.  2.  3.5 4. ]


['1' '2' '3' '4']


[   1    2    4 -128]


['ram' 'shya' 'hari' 'murl']


[False  True  True False  True False]


[None 1 2]


[ True False False]




In [5]:
#DIMENSIONS UPTO 64 DIMENSIONS
ar=np.array([1,2,3,4]) #rows
print(ar)

print("\n")

arr=np.array(([1,2,3],[4,5,6],[7,8,9])) #rowsxcol 2D
print(arr)

print("\n")

arrr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,1,1],[2,2,2],[3,3,3]]]) #3D
print(arrr)

print("\n")

arrrr=np.array([1,2,3,4],ndmin=32)
print(arrrr) 

print("\n")

[1 2 3 4]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]


[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]




In [6]:
#VIEW
import numpy as np
ar=np.array([11,33,44,55,66])
arr=np.array(([[1,2,3],[4,5,6],[7,8,9]]))
arrr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,1,1],[2,2,2],[3,3,3]]])
print(ar)
print(arr)
print(arrr)

print("\n")

print(ar.shape) #rows
print(arr.shape) #rows,col
print(arrr.shape) #vector,rows,col

print("\n")

print(ar.size)  #count of elements inside array
print(arr.size)
print(arrr.size)

print("\n")

print(ar.ndim)
print(arr.ndim)
print(arrr.ndim)

print("\n")

print(ar.dtype)
print(arr.dtype)
print(arrr.dtype)


[11 33 44 55 66]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]


(5,)
(3, 3)
(2, 3, 3)


5
9
18


1
2
3


int64
int64
int64


In [7]:
#type casting

print(ar.astype('int32')) #change data type temperory
print(ar.dtype)   #remains original 64

[11 33 44 55 66]
int64


In [8]:
#SLICING

#ID
print(ar)
print(ar[0])
print(ar[-1])
print(ar[0:2])
print(ar[0:5:2])
print(ar[-1:-6:-1])
print("\n")

#2D
print(arr)
print(arr[0])
print(arr[-1])
print(arr[0:2])
print(arr[-1:-4:-1])
print(arr[0:3:2])
print(arr[0:2,0]) #row_start:row_end , col_start:col_end
print(arr[0:2,0:2])
print("\n")

#3D
print(arrr)
print(arrr[0])
print(arrr[0:1])
print(arrr[0,0])
print(arrr[0,0,0:2]) #vector,row,col
print(arrr[0,:,2])



[11 33 44 55 66]
11
66
[11 33]
[11 44 66]
[66 55 44 33 11]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[7 8 9]
[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [7 8 9]]
[1 4]
[[1 2]
 [4 5]]


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3]
[1 2]
[3 6 9]


In [ ]:
#ITEM ASSIGNMENT
print(arr)
arr[0]=[11,12,33]
print(arr)
print('\n')

arr[1]=100
print(arr)

[[ 11  12  33]
 [100 100 100]
 [  7   8   9]]
[[ 11  12  33]
 [100 100 100]
 [  7   8   9]]


[[ 11  12  33]
 [100 100 100]
 [  7   8   9]]


In [41]:
#GENERATE
print(np.arange(1,10))
print(np.arange(1,10,2))
print(np.arange(-1,-10,-1))
print(np.zeros(10))
print(np.zeros((5,5)))
print(np.ones((2,2)))
print(np.full((2,2),'sana'))
print(np.full((2,2),17))
print(np.random.randint(1,100,5))
print(np.random.randn(10))  #any number in this randn will lie between -3 to +3
print(np.repeat([1,2,3],3)) #one by one krke repeat
print(np.repeat(['daily','monthly','weekly'],3))
print(np.tile([1,2,1],5))  #sequence mei repeat
print(np.tile(['daily','weekly'],5))
print(np.eye(5))  #diagonally 1 comes in identity matrix
print(np.linspace(1,100,4)) #equal space wale number generate in a list


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[['sana' 'sana']
 ['sana' 'sana']]
[[17 17]
 [17 17]]
[26 15  5 92 15]
[-0.11677123  0.03151544  0.37594025  1.22556684 -0.67820181 -0.75177782
  0.62918569 -1.64481385  0.80291411 -1.54994162]
[1 1 1 2 2 2 3 3 3]
['daily' 'daily' 'daily' 'monthly' 'monthly' 'monthly' 'weekly' 'weekly'
 'weekly']
[1 2 1 1 2 1 1 2 1 1 2 1 1 2 1]
['daily' 'weekly' 'daily' 'weekly' 'daily' 'weekly' 'daily' 'weekly'
 'daily' 'weekly']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[  1.  34.  67. 100.]


In [43]:
#generate 8 by 8 array of chessbox 
chess=np.zeros((8,8))
print(chess)
print('\n')
chess[::2,::2]=1
print(chess)
print("\n")
chess[1::2,1::2]=1
print(chess)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
