In [1]:
import numpy as np

In [ ]:
ar=np.random.choice(['low','medium','high'],50)
print(ar)
print("\n")

print(np.unique(ar))  #distinct elements
print(len(np.unique(ar)))
print(np.unique(ar,return_counts=True))  #how many times repeating

['medium' 'high' 'high' 'medium' 'medium' 'medium' 'high' 'medium'
 'medium' 'high' 'high' 'high' 'high' 'medium' 'high' 'high' 'medium'
 'high' 'medium' 'low' 'medium' 'medium' 'medium' 'low' 'high' 'medium'
 'low' 'low' 'high' 'medium' 'high' 'high' 'high' 'medium' 'medium' 'low'
 'medium' 'high' 'medium' 'low' 'high' 'medium' 'high' 'high' 'medium'
 'high' 'low' 'low' 'high' 'high']


['high' 'low' 'medium']
3
(array(['high', 'low', 'medium'], dtype='<U6'), array([22,  8, 20]))


In [ ]:
qty=np.random.randint(1,14,100)
print(qty)
print(np.histogram(qty,bins=3))  #range mei dalke ki uss range ke kitne records hai

[10  9 10  6 11  9 12  5  9  1  9  2 10  3  9  8 12 12 12 13  3  2  9 10
  7  7  4  8  7  8  4 11 13  4  2 11  5  8  6  3  1 13  2  5  4 10 13  6
 10 10  5  3  1  3  4  7 13  3  3  4  7  9  3  8  7  4  2 11  1  1  7  3
  7  1 10 10  5 13  4  8  8  9 13  9 11 10 11  6  3  3  3 13  3  8 12  9
  7  7  7  5]
(array([32, 29, 39]), array([ 1.,  5.,  9., 13.]))


In [ ]:
ar=np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.8,0.9])
print(np.round(ar)) #increasing mei round
print(np.floor(ar))  #dec mei round
print(np.ceil(ar))   


[0. 0. 0. 0. 0. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
